name: Build Dev Branch
run-name: '[build] "${{ github.event.head_commit.message }}"'
on:
  pull_request:
    branches:
      - dev

env:
  actions: TravelSizedLions/actions/.github/workflows
  
jobs:
  dump:
    name: Inspect
    uses: ${{env.actions}}/dump-vars.yaml@dev

  run-tests:
    name: Verify
    uses: ${{env.actions}}/test-drive.yaml@dev
  
  version-bump:
    name: Versioning
    needs: run-tests
    uses: ${{env.actions}}/bump-patch.yaml@dev
