name: Build Dev Branch
run-name: '[build] "${{ github.event.head_commit.message }}"'
on:
  pull_request:
    branches: ["dev"]

jobs:
  dump:
    name: Inspect
    uses: ./.github/workflows/dump-vars.yaml

  run-tests:
    name: Verify
    uses: TravelSizedLions/actions/.github/workflows/merge-request.yaml@dev
  
  version-bump:
    name: Versioning
    needs: run-tests
    uses: ./.github/workflows/bump-versions.yaml
