name: Bump patch version
on:
  workflow_call:

jobs:
  bump-version:
    name: Bump patch version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dasel
        run: sudo apt-get install -y dasel

      - name: Change Permissions
        run: chmod +x ./scripts/version-bump-addons.sh && chmod +x ./scripts/version-bump-plugin.sh

      - name: Bump addons
        run: ./scripts/version-bump-addons.sh ${{ github.event.repository.name }}

      - name: Bump plugin
        run: ./scripts/version-bump-plugin.sh ${{ github.event.repository.name }}

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version"
          tagging_message: "v$NEXT_VERSION"
