name: Bump addons.jsonc patch version
on:
  workflow_call:

jobs:
  bump-version:
    name: Bump addons.jsonc patch version
    runs-on: ubuntu-24.04
    steps:
      - name: ls
        run: pwd && ls -a

      - name: bump
        run: scripts/version-bump-addons.sh ${{ github.event.repository.name }}
