name: Merge Request
run-name: '#${{github.event.pull_request.number}}: "${{github.event.pull_request.title}}" [${{github.actor}}]'
on:
  pull_request:
    branches: ["asdf"]
  push:
    branches: ["asdf"]

jobs:
  unit-tests:
    uses: TravelSizedLions/actions/.github/workflows/merge-request.yaml@dev
